[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "efcli"
version = "0.1.0"
description = "Wrapper de pyhanko para operar firmas digitales PAdES en el contexto de la PKI de Banxico y el SAT."
authors = [
	{ name = "Juan José CB", email = "juan.josecb02@gmail.com" },
]
license = "GPL-3.0"

requires-python = ">=3.11"
dependencies = [
	"pyhanko==0.34.1",
    "pikepdf==10.5.1",
    "aiohttp",
    "colorama==0.4.6"
]

[project.urls]
homepage = "https://github.com/juan-jcb/e.firma-CLI.git"
repository = "https://github.com/juan-jcb/e.firma-CLI.git"

[project.scripts]
efcli = "efcli.main:main"
